name: Building binary releases

on: 
  workflow_dispatch

permissions:
  contents: write

jobs:
  build_pkg:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install prerequisites
      run: |
        cd /tmp/
        APT_PARAMS='sudo apt -y -qq -o=Dpkg::Use-Pty=0'
        $APT_PARAMS update
        $APT_PARAMS install curl git
        curl -fsSL https://get.pnpm.io/install.sh | sh -
        source /home/runner/.bashrc

    - name: Build 
      run: |
        cd /tmp/
        #source /home/runner/.bashrc
        PNPM_BIN="/home/runner/.local/share/pnpm/pnpm"
        git clone "https://github.com/SphericalKat/medium.rip.git"
        
        cd "/tmp/medium.rip/frontend/"
        mv postcss.config.ts postcss.config.cjs
        $PNPM_BIN i
        $PNPM_BIN approve-builds
        $PNPM_BIN run build

        cd "/tmp/medium.rip/"
        go mod download
        go build -ldflags='-w -s -extldflags "-static"' .
        
        ls -alh medium.rip && file medium.rip
        
        
        
        
        
