name: Building binary releases

on: 
  workflow_dispatch

permissions:
  contents: write

jobs:
  build_pkg:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install prerequisites
      run: |
        cd /tmp/
        
